name: Documentation

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    if: startsWith(github.event.head_commit.message, 'doc:') || startsWith(github.event.head_commit.message, 'docs:')
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install -g @compodoc/compodoc

      - name: Build documentation
        run: compodoc --theme material -p tsconfig.doc.json

      - name: Deploy GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./documentation
